spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OmerKurtuldu/turkcellCRM-config-server.git
  profiles:
    active: dev
server:
  port: 8050