eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 9006
spring:
  application:
    name: search-service
  data:
    mongodb:
      database: turkcellcrmcustomerdb
      uri: mongodb://localhost:27017

